project_id = "pqgidznijhsaboqqofhn"

[functions.netplex-ai]
verify_jwt = false

[functions.redeem-invite]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.image-search]
verify_jwt = false
