// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-listings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function client() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search listings",
  description: "Search available NetPlex marketplace listings by keyword, category slug, region, brand, or price range. Returns up to 20 results ordered by newest.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text search on title/brand/model."),
    category_slug: z.string().trim().optional().describe("Category slug filter, e.g. 'phones'."),
    region: z.string().trim().optional().describe("Region filter (Arabic name)."),
    brand: z.string().trim().optional(),
    min_price_ils: z.number().nonnegative().optional(),
    max_price_ils: z.number().positive().optional(),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    const supabase = client();
    let q = supabase.from("listings").select("id,title,price_ils,region,brand,model,condition,category_id,seller_id,view_count,created_at").eq("status", "available").order("created_at", { ascending: false }).limit(input.limit ?? 20);
    if (input.query) {
      const term = `%${input.query}%`;
      q = q.or(`title.ilike.${term},brand.ilike.${term},model.ilike.${term}`);
    }
    if (input.region) q = q.eq("region", input.region);
    if (input.brand) q = q.ilike("brand", input.brand);
    if (input.min_price_ils != null) q = q.gte("price_ils", input.min_price_ils);
    if (input.max_price_ils != null) q = q.lte("price_ils", input.max_price_ils);
    if (input.category_slug) {
      const { data: cat } = await supabase.from("categories").select("id").eq("slug", input.category_slug).maybeSingle();
      if (cat?.id) q = q.eq("category_id", cat.id);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "Get listing details",
  description: "Fetch full details for a single NetPlex listing by its ID.",
  inputSchema: {
    listing_id: z2.string().uuid().describe("Listing UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ listing_id }) => {
    const supabase = client2();
    const { data, error } = await supabase.from("listings").select("*").eq("id", listing_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Listing not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { listing: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function client3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all NetPlex marketplace categories with their slugs and names.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = client3();
    const { data, error } = await supabase.from("categories").select("id,slug,name_ar,name_en,icon").order("name_ar");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-verified-sellers.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_verified_sellers_default = defineTool4({
  name: "list_verified_sellers",
  title: "List verified sellers",
  description: "List verified NetPlex sellers ordered by trust score. Optionally filter by region.",
  inputSchema: {
    region: z3.string().trim().optional(),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ region, limit }) => {
    const supabase = client4();
    let q = supabase.from("sellers_public").select("id,user_id,shop_name,region,trust_score,verified").eq("verified", true).order("trust_score", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (region) q = q.eq("region", region);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sellers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "netplex-mcp",
  title: "NetPlex Marketplace",
  version: "0.1.0",
  instructions: "Tools for the NetPlex Gaza marketplace. Use `list_categories` to discover category slugs, `search_listings` to find available products by keyword / category / region / brand / price, `get_listing` to fetch a single product's full details, and `list_verified_sellers` to browse trusted shops. All data is public and read-only.",
  tools: [search_listings_default, get_listing_default, list_categories_default, list_verified_sellers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
